# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-21 14:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.IntegerField(max_length=10)),
                ('task_data', models.CharField(max_length=500)),
                ('task_output', models.CharField(max_length=500)),
                ('task_created_by', models.DateTimeField()),
            ],
        ),
    ]
