# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-24 07:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webfetchapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='twitter_data',
            fields=[
                ('twitter_id', models.AutoField(primary_key=True, serialize=False)),
                ('twitter_text', models.TextField(max_length=5000)),
                ('twitter_user_screen_name', models.CharField(max_length=5000)),
                ('twitter_favourite_count', models.CharField(max_length=300)),
                ('twitter_retwited_count', models.CharField(max_length=300)),
                ('twitter_user_language', models.CharField(max_length=1000)),
                ('twitter_user_location', models.CharField(max_length=1000)),
                ('twitter_post_created', models.CharField(max_length=1000)),
            ],
        ),
    ]
