# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-24 13:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('webfetchapp', '0002_twitter_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='twitter_data',
            name='request_id',
            field=models.CharField(default=datetime.datetime(2016, 10, 24, 13, 41, 17, 226193, tzinfo=utc), max_length=300),
            preserve_default=False,
        ),
    ]
