# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-25 11:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webfetchapp', '0003_twitter_data_request_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='facebook_data',
            fields=[
                ('facebook_id', models.AutoField(primary_key=True, serialize=False)),
                ('request_id', models.CharField(max_length=300)),
                ('fb_post_id', models.CharField(max_length=300)),
                ('fb_post_message', models.TextField(max_length=5000)),
                ('fb_post_from', models.CharField(max_length=300)),
                ('fb_post_share_count', models.CharField(max_length=300)),
                ('fb_post_like_count', models.CharField(max_length=300)),
                ('fb_post_comment_count', models.CharField(max_length=1000)),
                ('fb_post_created_date', models.CharField(max_length=1000)),
            ],
        ),
    ]
