# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-26 06:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webfetchapp', '0004_facebook_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='youtube_data',
            fields=[
                ('youtube_id', models.AutoField(primary_key=True, serialize=False)),
                ('request_id', models.CharField(max_length=300)),
                ('video_title', models.CharField(max_length=5000)),
                ('video_description', models.CharField(max_length=5000)),
                ('video_posted_by', models.CharField(max_length=1000)),
                ('video_like_count', models.CharField(max_length=300)),
                ('video_share_count', models.CharField(max_length=300)),
                ('video_created_date', models.CharField(max_length=300)),
            ],
        ),
    ]
